controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
articles_api:
   path: /api/articles
   controller: 'App\Controller\ArticlesController::index'
   methods: ['GET']

articles_api_show:
   path: /api/article/{id}
   controller: 'App\Controller\ArticlesController::show'
   methods: ['GET']

articles_api_create:
   path: /api/article/add
   controller: 'App\Controller\ArticlesController::create'
   methods: ['POST']

articles_api_update:
   path: /api/article/{id}
   controller: 'App\Controller\ArticlesController::update'
   methods: ['PUT']

articles_api_delete:
   path: /api/article/{id}
   controller: 'App\Controller\ArticlesController::delete'
   methods: ['DELETE']

product_api_search:
   path: /api/articles/search/{keyword}
   controller: 'App\Controller\ArticlesController::search'
   methods: ['GET']
